import { FinancialPersonaPreset } from '../types/pfm';

export const FINANCIAL_PRESETS: FinancialPersonaPreset[] = [
  {
    id: 'preset-graduate',
    name: '20대 사회초년생',
    tagline: '월급 280만 원 · 배달/외식 & 택시 과다 지출형',
    data: {
      year: 2026,
      month: 10,
      income: 2800000,
      budget: 1800000,
      userGoal: '1년 내 비상금 1,000만 원 모으기 및 청약 납입',
      expenses: [
        {
          id: 'exp-1',
          name: '식비 & 배달음식',
          category: '식비/외식',
          budgetAmount: 350000,
          actualAmount: 580000,
          isUnplanned: false,
          note: '주 4회 야식 배달 주문 누적',
        },
        {
          id: 'exp-2',
          name: '원룸 월세 및 공과금',
          category: '주거/통신',
          budgetAmount: 500000,
          actualAmount: 520000,
          isUnplanned: false,
        },
        {
          id: 'exp-3',
          name: '교통비 & 심야 택시',
          category: '교통/차량',
          budgetAmount: 120000,
          actualAmount: 215000,
          isUnplanned: false,
          note: '야근 후 및 주말 모임 심야 카카오택시 빈번',
        },
        {
          id: 'exp-4',
          name: '카페 & 디저트 음료',
          category: '식비/외식',
          budgetAmount: 90000,
          actualAmount: 165000,
          isUnplanned: false,
          note: '출근길 및 점심 후 프랜차이즈 커피 일 2잔',
        },
        {
          id: 'exp-5',
          name: '패션 & 생활 쇼핑',
          category: '쇼핑/생활',
          budgetAmount: 150000,
          actualAmount: 195000,
          isUnplanned: false,
        },
        {
          id: 'exp-6',
          name: '스마트폰 요금 & 구독(OTT)',
          category: '주거/통신',
          budgetAmount: 110000,
          actualAmount: 118000,
          isUnplanned: false,
        },
        {
          id: 'exp-7',
          name: '실손의료보험',
          category: '금융/보험',
          budgetAmount: 50000,
          actualAmount: 50000,
          isUnplanned: false,
        },
        {
          id: 'exp-8',
          name: '친구 결혼식 축의금 및 교통',
          category: '경조사/기타',
          budgetAmount: 0,
          actualAmount: 150000,
          isUnplanned: true,
          note: '동기 청첩장 모임 및 축의금 (예산 외 발생)',
        },
      ],
    },
  },
  {
    id: 'preset-family',
    name: '30대 외벌이 3인 가구',
    tagline: '월수입 480만 원 · 주담대 상환 & 돌발 가전 수리비 발생',
    data: {
      year: 2026,
      month: 10,
      income: 4800000,
      budget: 3700000,
      userGoal: '주담대 조기상환 및 자녀 교육비 펀드 시작',
      expenses: [
        {
          id: 'fam-1',
          name: '아파트 주택담보대출 원리금',
          category: '주거/통신',
          budgetAmount: 1200000,
          actualAmount: 1200000,
          isUnplanned: false,
        },
        {
          id: 'fam-2',
          name: '가족 장보기 및 식자재',
          category: '식비/외식',
          budgetAmount: 900000,
          actualAmount: 1140000,
          isUnplanned: false,
          note: '추석 전후 과일·육류 물가 상승 영향',
        },
        {
          id: 'fam-3',
          name: '자녀 학습지 및 예체능 학원',
          category: '교육/자기계발',
          budgetAmount: 600000,
          actualAmount: 650000,
          isUnplanned: false,
        },
        {
          id: 'fam-4',
          name: '차량 유류비 및 주차비',
          category: '교통/차량',
          budgetAmount: 300000,
          actualAmount: 390000,
          isUnplanned: false,
        },
        {
          id: 'fam-5',
          name: '가족 종합보험료',
          category: '금융/보험',
          budgetAmount: 350000,
          actualAmount: 350000,
          isUnplanned: false,
        },
        {
          id: 'fam-6',
          name: '아파트 관리비 및 도시가스',
          category: '주거/통신',
          budgetAmount: 250000,
          actualAmount: 285000,
          isUnplanned: false,
        },
        {
          id: 'fam-7',
          name: '세탁기 긴급 고장 수리비',
          category: '쇼핑/생활',
          budgetAmount: 0,
          actualAmount: 185000,
          isUnplanned: true,
          note: '모터 부품 교체 긴급 출장 수리 (예산 외)',
        },
        {
          id: 'fam-8',
          name: '양가 부모님 명절 선물/외식',
          category: '경조사/기타',
          budgetAmount: 0,
          actualAmount: 300000,
          isUnplanned: true,
          note: '명절 가족 모임 외식비 (예산 외)',
        },
      ],
    },
  },
  {
    id: 'preset-freelancer',
    name: '1인 가구 프리랜서',
    tagline: '월수입 390만 원 · 유동성 확보 & 소프트웨어 구독 관리형',
    data: {
      year: 2026,
      month: 10,
      income: 3900000,
      budget: 2200000,
      userGoal: '종합소득세 유보금 확보 및 안정적 연금 마련',
      expenses: [
        {
          id: 'free-1',
          name: '오피스텔 월세 및 관리비',
          category: '주거/통신',
          budgetAmount: 650000,
          actualAmount: 650000,
          isUnplanned: false,
        },
        {
          id: 'free-2',
          name: '외식 및 클라이언트 미팅',
          category: '식비/외식',
          budgetAmount: 500000,
          actualAmount: 620000,
          isUnplanned: false,
        },
        {
          id: 'free-3',
          name: '업무용 SaaS 및 AI 구독료',
          category: '문화/여가',
          budgetAmount: 140000,
          actualAmount: 175000,
          isUnplanned: false,
          note: '환율 상승으로 해외 결제 소프트웨어 비용 증가',
        },
        {
          id: 'free-4',
          name: '공유오피스 & 작업 카페',
          category: '식비/외식',
          budgetAmount: 150000,
          actualAmount: 190000,
          isUnplanned: false,
        },
        {
          id: 'free-5',
          name: '국민연금 및 건강보험(지역가입)',
          category: '금융/보험',
          budgetAmount: 300000,
          actualAmount: 300000,
          isUnplanned: false,
        },
        {
          id: 'free-6',
          name: '교통비 (지하철/KTX 출장)',
          category: '교통/차량',
          budgetAmount: 120000,
          actualAmount: 135000,
          isUnplanned: false,
        },
        {
          id: 'free-7',
          name: '업무 모니터 보조 스탠드 교체',
          category: '쇼핑/생활',
          budgetAmount: 0,
          actualAmount: 140000,
          isUnplanned: true,
          note: '작업 환경 개선 장비 구매 (예산 외)',
        },
      ],
    },
  },
  {
    id: 'preset-double-income',
    name: '신혼부부 맞벌이',
    tagline: '합산 수입 720만 원 · 고소득 자산증식 & 예산 통제 모범형',
    data: {
      year: 2026,
      month: 10,
      income: 7200000,
      budget: 3400000,
      userGoal: '청약 당첨 계약금 마련 및 절세 ISA 계좌 한도 채우기',
      expenses: [
        {
          id: 'di-1',
          name: '전세대출 이자 & 아파트 관리비',
          category: '주거/통신',
          budgetAmount: 950000,
          actualAmount: 950000,
          isUnplanned: false,
        },
        {
          id: 'di-2',
          name: '부부 식비 & 주말 데이트 외식',
          category: '식비/외식',
          budgetAmount: 900000,
          actualAmount: 1080000,
          isUnplanned: false,
        },
        {
          id: 'di-3',
          name: '양가 부모님 정기 용돈',
          category: '경조사/기타',
          budgetAmount: 400000,
          actualAmount: 400000,
          isUnplanned: false,
        },
        {
          id: 'di-4',
          name: '차량 유류비 및 보험료 분납',
          category: '교통/차량',
          budgetAmount: 400000,
          actualAmount: 430000,
          isUnplanned: false,
        },
        {
          id: 'di-5',
          name: '부부 헬스장 및 필라테스',
          category: '의료/건강',
          budgetAmount: 300000,
          actualAmount: 300000,
          isUnplanned: false,
        },
        {
          id: 'di-6',
          name: '부부 통신비 & 인터넷/TV',
          category: '주거/통신',
          budgetAmount: 150000,
          actualAmount: 145000,
          isUnplanned: false,
        },
        {
          id: 'di-7',
          name: '마켓컬리 & 생활 생필품',
          category: '쇼핑/생활',
          budgetAmount: 200000,
          actualAmount: 240000,
          isUnplanned: false,
        },
        {
          id: 'di-8',
          name: '환절기 침구류 및 패딩 세탁',
          category: '쇼핑/생활',
          budgetAmount: 0,
          actualAmount: 160000,
          isUnplanned: true,
          note: '계절 전환 드라이클리닝 & 이불 교체 (예산 외)',
        },
      ],
    },
  },
];
